### ISSUE TITLE
Using mkjobtexmf to get list of dependent files

### ISSUE THREAD

**Issue by duetosymmetry** [vijayvarma392/paper_template#1]
For the submission script, I switched to using `mkjobtexmf` to get the list of dependent files, instead of building it manually. Let me know if you want the updated code, otherwise feel free to close this issue.

**Comment by vijayvarma392** [comment]
Sure. Do you want to add it to this repo? I can make you a collaborator.

**Comment by duetosymmetry** [comment]
Closed by #2
